name: Qodo Cover
description: "Runs the Qodo Cover agent to generate tests."
author: QodoAI

inputs:
  github_token:
    description: "GitHub token for authentication"
    required: true
  project_language:
    description: "Language of the project"
    required: false
    default: "python"
  project_root:
    description: "Root directory of the project"
    required: false
    default: "."
  diff_coverage:
    description: "When true, only target coverage for lines in the diff"
    required: false
    default: "false"
  branch:
    description: "The base branch to compare to for diff_coverage"
    required: false
    default: "main"
  code_coverage_report_path:
    description: "Path to the coverage.xml"
    required: false
    default: "./coverage.xml"
  coverage_type:
    description: "Type of coverage report, e.g. 'cobertura' or 'jacoco'."
    required: false
    default: "cobertura"
  test_command:
    description: "Command to run tests, e.g. 'pytest --cov=. --cov-report=xml --cov-report=term'"
    required: true
  model:
    description: "LLM model name, e.g. 'gpt-4o'"
    required: false
    default: "gpt-4o"
  max_iterations:
    description: "Maximum number test generation attempts per test file"
    required: false
    default: "3"
  desired_coverage:
    description: "Desired coverage percentage"
    required: false
    default: "100"
  run_each_test_separately:
    description: "Whether the agent should modify the test command to run individual tests"
    required: false
    default: "true"
  source_folder:
    description: "Path, relative to project_root, to look for source files. Will ignore source files outside this folder. Defaults to `.`"
    required: false
    default: "."
  test_folder:
    description: "Path, relative to project_root, to look for test files. Will ignore test files outside this folder. Defaults to `.`"
    required: false
    default: "."
  additional_instructions:
    description: "Additional instructions you wish to append at the end of the test generation prompt."
    required: false
    default: "generated tests MUST be prefixed by a comment that says 'This test was generated by Qodo Cover'"
  api_base:                        # 新增项
    description: "Custom API base URL"
    required: false
    default: ""
runs:
  using: "composite"
  steps:

    - name: Run script
      run: |
        ${{ github.action_path }}/scripts/run.sh \
          --pr-number "${{ github.event.pull_request.number }}" \
          --pr-ref "${{ github.event.pull_request.head.ref }}" \
          --project-language "${{ inputs.project_language }}" \
          --project-root "${{ inputs.project_root }}" \
          --diff-coverage "${{ inputs.diff_coverage }}" \
          --branch "${{ inputs.branch }}" \
          --code-coverage-report-path "${{ inputs.code_coverage_report_path }}" \
          --coverage-type "${{ inputs.coverage_type }}" \
          --test-command "${{ inputs.test_command }}" \
          --model "${{ inputs.model }}" \
          --max-iterations "${{ inputs.max_iterations }}" \
          --desired-coverage "${{ inputs.desired_coverage }}" \
          --run-each-test-separately "${{ inputs.run_each_test_separately }}" \
          --source-folder "${{ inputs.source_folder }}" \
          --test-folder "${{ inputs.test_folder }}" \
          --additional-instructions "${{ inputs.additional_instructions }}" \
          --action-path "${{ github.action_path }}" \
          --api-base "${{ inputs.api_base }}" \
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        ACTION_REF: ${{ github.action_ref }}
      shell: bash
